I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 659, in script
    show alla amazed dissolve
Exception: Image 'alla amazed' does not accept attributes 'dissolve'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 659, in script
    show alla amazed dissolve
  File "C:\Users\Evgen\OneDrive\Desktop\ren.py\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Evgen\OneDrive\Desktop\ren.py\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Evgen\OneDrive\Desktop\ren.py\renpy\exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Evgen\OneDrive\Desktop\ren.py\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Evgen\OneDrive\Desktop\ren.py\renpy\display\core.py", line 499, in _duplicate
    args.extraneous()
  File "C:\Users\Evgen\OneDrive\Desktop\ren.py\renpy\display\core.py", line 362, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'alla amazed' does not accept attributes 'dissolve'.

Windows-10-10.0.22000 AMD64
Ren'Py 8.1.3.23091805
Код из Космоса 1.0
Mon Dec  4 20:49:11 2023
